sudo: required
services:
    - docker
before_install:
    - docker build -t deepakbhatt74/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true deepakbhatt74/docker-react npm run test
deploy:
        provider: elasticbeanstalk
        region: "us-east-1"
        app: "docker-react"
        env: "DockerReact-env"
        bucket_name: "elasticbeanstalk-us-east-1-349541656667"
        bucket_path: "docker-react"
        on:
            branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY